version: '3.6'
services:

  strapi:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: toor
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - "8086:5432"

  adminer:
    image: adminer:4.7.1
    restart: always
    ports:
      - 8080:8080

volumes:
  strapi-data:
